### ISSUE TITLE
Remove pyc files

### ISSUE THREAD

**Issue by rodo** [kimeshan/mixpanel-puller#7]
Hi,
I'm not already uses Mixpanel but we may use it in a near future, as we already use PostgreSQL I found your project and think about use it.
I saw you push to github `*.pyc` files that is not recommended, what about remove them ? 
If you agree I'll push a PR to remove them and add a `.gitignore` file too that excludes `pyc` files

**Comment by kimeshan** [comment]
Hi @rodo , sure good find with the *.pyc files. Please go ahead and submit a PR to dev branch. Thanks

**Comment by rodo** [comment]
Thanks for your quick answer @kimeshan

**Comment by mmequignon** [comment]
Hi,
I've noticed that you also have pushed `*.pyo` and `*.pyd` files.
It is actually not interesting to commit them.
Do you mind if I improve the `.gitignore` in order to remove them ?

**Comment by kimeshan** [comment]
@mmequignon Sure, can you create a new issue as I'm closing this one. Also, instead of just adding them to the .gitignore - you can add a requirements.txt and remove the dependency folders that shouldn't be a part of this.
